export const PLATFORMS = [
  // ── Integrated platforms ──────────────────────────────────────────────────
  {
    id: 'google',
    displayName: 'Google',
    logo: '/hearsay/logos/google.svg',
    endpoint: 'google',
    brandColor: '#4285F4',
    defaultEnabled: true,
    supportsLocation: true,
    integrated: true,
  },
  {
    id: 'yelp',
    displayName: 'Yelp',
    logo: '/hearsay/logos/yelp.svg',
    endpoint: 'yelp',
    brandColor: '#FF1A1A',
    defaultEnabled: true,
    supportsLocation: true,
    integrated: true,
  },
  {
    id: 'reddit',
    displayName: 'Reddit',
    logo: '/hearsay/logos/reddit.svg',
    endpoint: 'reddit',
    brandColor: '#FF4500',
    defaultEnabled: true,
    supportsLocation: true,
    integrated: true,
    working: false, // API creds pending — greyed out and not queried for now
  },
  {
    id: 'youtube',
    displayName: 'YouTube',
    logo: '/hearsay/logos/youtube.svg',
    endpoint: 'youtube',
    brandColor: '#FF0000',
    defaultEnabled: true,
    supportsLocation: true,
    integrated: true,
  },
  {
    id: 'tripadvisor',
    displayName: 'TripAdvisor',
    logo: '/hearsay/logos/tripadvisor.svg',
    endpoint: 'tripadvisor',
    brandColor: '#34E0A1',
    defaultEnabled: true,
    supportsLocation: true,
    integrated: true,
  },
  {
    id: 'facebook',
    displayName: 'Facebook',
    logo: '/hearsay/logos/facebook.svg',
    endpoint: 'facebook',
    brandColor: '#1877F2',
    defaultEnabled: true,
    supportsLocation: true,
    label: 'Facebook Mentions',
    integrated: true,
  },
  {
    id: 'trustpilot',
    displayName: 'Trustpilot',
    logo: '/hearsay/logos/trustpilot.svg',
    endpoint: 'trustpilot',
    brandColor: '#00B67A',
    defaultEnabled: true,
    supportsLocation: false,
    integrated: true,
  },

  // ── Coming-soon platforms ─────────────────────────────────────────────────
  {
    id: 'opentable',
    displayName: 'OpenTable',
    logo: '/hearsay/logos/opentable.svg',
    brandColor: '#DA3743',
    defaultEnabled: false,
    integrated: false,
  },
  {
    id: 'nextdoor',
    displayName: 'Nextdoor',
    logo: '/hearsay/logos/nextdoor.svg',
    brandColor: '#8ED500',
    defaultEnabled: false,
    integrated: false,
  },
  {
    id: 'foursquare',
    displayName: 'Foursquare',
    logo: '/hearsay/logos/foursquare.svg',
    brandColor: '#F94877',
    defaultEnabled: false,
    integrated: false,
  },
  {
    id: 'thefork',
    displayName: 'TheFork',
    logo: '/hearsay/logos/thefork.svg',
    brandColor: '#00B163',
    defaultEnabled: false,
    integrated: false,
  },
  {
    id: 'michelin',
    displayName: 'Michelin',
    logo: '/hearsay/logos/michelin.svg',
    brandColor: '#E4251B',
    defaultEnabled: false,
    integrated: false,
  },
  {
    id: 'justdial',
    displayName: 'JustDial',
    logo: '/hearsay/logos/justdial.svg',
    brandColor: '#E91E2C',
    defaultEnabled: false,
    integrated: false,
  },
  {
    id: 'magicpin',
    displayName: 'Magicpin',
    logo: '/hearsay/logos/magicpin.svg',
    brandColor: '#E01B24',
    defaultEnabled: false,
    integrated: false,
  },
  {
    id: 'zomato',
    displayName: 'Zomato',
    logo: '/hearsay/logos/zomato.svg',
    brandColor: '#E23744',
    defaultEnabled: false,
    integrated: false,
  },
  {
    id: 'swiggy',
    displayName: 'Swiggy',
    logo: '/hearsay/logos/swiggy.svg',
    brandColor: '#FC8019',
    defaultEnabled: false,
    integrated: false,
  },
  {
    id: 'dianping',
    displayName: 'Dianping',
    logo: '/hearsay/logos/dianping.svg',
    brandColor: '#FF6633',
    defaultEnabled: false,
    integrated: false,
  },
  {
    id: 'meituan',
    displayName: 'Meituan',
    logo: '/hearsay/logos/meituan.svg',
    brandColor: '#FFD100',
    defaultEnabled: false,
    integrated: false,
  },
  {
    id: 'baidumaps',
    displayName: 'Baidu Maps',
    logo: '/hearsay/logos/baidumaps.svg',
    brandColor: '#2932E1',
    defaultEnabled: false,
    integrated: false,
  },
  {
    id: 'gaode',
    displayName: 'Gaode',
    logo: '/hearsay/logos/gaode.svg',
    brandColor: '#1677FF',
    defaultEnabled: false,
    integrated: false,
  },
  {
    id: 'xiaohongshu',
    displayName: 'Xiaohongshu',
    logo: '/hearsay/logos/xiaohongshu.svg',
    brandColor: '#FF2442',
    defaultEnabled: false,
    integrated: false,
  },
  {
    id: 'wechat',
    displayName: 'WeChat',
    logo: '/hearsay/logos/wechat.svg',
    brandColor: '#07C160',
    defaultEnabled: false,
    integrated: false,
  },
  {
    id: 'grabfood',
    displayName: 'GrabFood',
    logo: '/hearsay/logos/grabfood.svg',
    brandColor: '#00B14F',
    defaultEnabled: false,
    integrated: false,
  },
  {
    id: 'agoda',
    displayName: 'Agoda',
    logo: '/hearsay/logos/agoda.svg',
    brandColor: '#5392FF',
    defaultEnabled: false,
    integrated: false,
  },
  {
    id: 'wongnai',
    displayName: 'Wongnai',
    logo: '/hearsay/logos/wongnai.svg',
    brandColor: '#FF1940',
    defaultEnabled: false,
    integrated: false,
  },
  {
    id: 'chope',
    displayName: 'Chope',
    logo: '/hearsay/logos/chope.svg',
    brandColor: '#E8472C',
    defaultEnabled: false,
    integrated: false,
  },
  {
    id: 'rappi',
    displayName: 'Rappi',
    logo: '/hearsay/logos/rappi.svg',
    brandColor: '#FF441F',
    defaultEnabled: false,
    integrated: false,
  },
  {
    id: 'degusta',
    displayName: 'Degusta',
    logo: '/hearsay/logos/degusta.svg',
    brandColor: '#E31219',
    defaultEnabled: false,
    integrated: false,
  },
  {
    id: 'talabat',
    displayName: 'Talabat',
    logo: '/hearsay/logos/talabat.svg',
    brandColor: '#FF6A00',
    defaultEnabled: false,
    integrated: false,
  },
]

export const PLATFORM_MAP = Object.fromEntries(PLATFORMS.map(p => [p.id, p]))
